const Prism = require("prismjs");
const PrismLoader = require("./PrismLoader");
const HighlightLinesGroup = require("./HighlightLinesGroup");

const Languages = {
  "abap": "ABAP",
  "abnf": "Augmented Backus–Naur form",
  "actionscript": "ActionScript",
  "ada": "Ada",
  "adoc": "AsciiDoc",
  "al": "AL",
  "alias": "ly",
  "antlr4": "ANTLR4",
  "apacheconf": "Apache Configuration",
  "apl": "APL",
  "applescript": "AppleScript",
  "aql": "AQL",
  "arduino": "Arduino",
  "arff": "ARFF",
  "asciidoc": "AsciiDoc",
  "asm6502": "6502 Assembly",
  "aspnet": "ASP.NET (C#)",
  "autohotkey": "AutoHotkey",
  "autoit": "AutoIt",
  "bash": "Bash",
  "basic": "BASIC",
  "batch": "Batch",
  "bbcode": "BBcode",
  "bison": "Bison",
  "bnf": "Backus–Naur form",
  "brainfuck": "Brainfuck",
  "brightscript": "BrightScript",
  "bro": "Bro",
  "c": "C",
  "cil": "CIL",
  "clike": "C-like",
  "clojure": "Clojure",
  "cmake": "CMake",
  "coffeescript": "CoffeeScript",
  "conc": "Concurnas",
  "concurnas": "Concurnas",
  "context": "ConTeXt",
  "cpp": "C++",
  "crystal": "Crystal",
  "cs": "C#",
  "csharp": "C#",
  "csp": "Content-Security-Policy",
  "css": "CSS",
  "css-extras": "CSS Extras",
  "d": "D",
  "dart": "Dart",
  "dax": "DAX",
  "diff": "Diff",
  "django": "Django/Jinja2",
  "dns-zone-file": "DNS zone file",
  "docker": "Docker",
  "dockerfile": "Docker",
  "dotnet": "C#",
  "ebnf": "Extended Backus–Naur form",
  "eiffel": "Eiffel",
  "ejs": "EJS",
  "elisp": "Lisp",
  "elixir": "Elixir",
  "elm": "Elm",
  "emacs": "Lisp",
  "emacs-lisp": "Lisp",
  "erb": "ERB",
  "erlang": "Erlang",
  "eta": "Eta",
  "etlua": "Embedded Lua templating",
  "excel-formula": "Excel Formula",
  "factor": "Factor",
  "firestore-security-rules": "Firestore security rules",
  "flow": "Flow",
  "fortran": "Fortran",
  "fsharp": "F#",
  "ftl": "FreeMarker Template Language",
  "g4": "ANTLR4",
  "gamemakerlanguage": "GameMaker Language",
  "gcode": "G-code",
  "gdscript": "GDScript",
  "gedcom": "GEDCOM",
  "gherkin": "Gherkin",
  "git": "Git",
  "glsl": "GLSL",
  "gml": "GameMaker Language",
  "go": "Go",
  "graphql": "GraphQL",
  "groovy": "Groovy",
  "haml": "Haml",
  "handlebars": "Handlebars",
  "haskell": "Haskell",
  "haxe": "Haxe",
  "hcl": "HCL",
  "hlsl": "HLSL",
  "hpkp": "HTTP Public-Key-Pins",
  "hs": "Haskell",
  "hsts": "HTTP Strict-Transport-Security",
  "html": "HTML",
  "http": "HTTP",
  "ichigojam": "IchigoJam",
  "icon": "Icon",
  "iecst": "Structured Text (IEC 61131-3)",
  "inform7": "Inform 7",
  "ini": "Ini",
  "io": "Io",
  "j": "J",
  "java": "Java",
  "javadoc": "JavaDoc",
  "javadoclike": "JavaDoc-like",
  "javascript": "JavaScript",
  "javastacktrace": "Java stack trace",
  "jinja2": "Django/Jinja2",
  "jolie": "Jolie",
  "jq": "JQ",
  "js": "JavaScript",
  "js-extras": "JS Extras",
  "js-templates": "JS Templates",
  "jsdoc": "JSDoc",
  "json": "JSON",
  "json5": "JSON5",
  "jsonp": "JSONP",
  "jsx": "React JSX",
  "julia": "Julia",
  "keyman": "Keyman",
  "kotlin": "Kotlin",
  "latex": "LaTeX",
  "latte": "Latte",
  "less": "Less",
  "lilypond": "LilyPond",
  "liquid": "Liquid",
  "lisp": "Lisp",
  "livescript": "LiveScript",
  "llvm": "LLVM IR",
  "lolcode": "LOLCODE",
  "lua": "Lua",
  "makefile": "Makefile",
  "markdown": "Markdown",
  "markup-templating": "Markup templating",
  "mathml": "MathML",
  "matlab": "MATLAB",
  "md": "Markdown",
  "mel": "MEL",
  "mizar": "Mizar",
  "monkey": "Monkey",
  "moon": "MoonScript",
  "moonscript": "MoonScript",
  "mscript": "PowerQuery",
  "n1ql": "N1QL",
  "n4js": "N4JS",
  "n4jsd": "N4JS",
  "nand2tetris-hdl": "Nand To Tetris HDL",
  "nasm": "NASM",
  "neon": "NEON",
  "nginx": "nginx",
  "nim": "Nim",
  "nix": "Nix",
  "nsis": "NSIS",
  "objc": "Objective-C",
  "objectivec": "Objective-C",
  "objectpascal": "Object Pascal",
  "ocaml": "OCaml",
  "opencl": "OpenCL",
  "oz": "Oz",
  "parigp": "PARI/GP",
  "parser": "Parser",
  "pascal": "Pascal",
  "pascaligo": "Pascaligo",
  "pcaxis": "PC-Axis",
  "pcode": "PeopleCode",
  "peoplecode": "PeopleCode",
  "perl": "Perl",
  "php": "PHP",
  "php-extras": "PHP Extras",
  "phpdoc": "PHPDoc",
  "plsql": "PL/SQL",
  "powerquery": "PowerQuery",
  "powershell": "PowerShell",
  "pq": "PowerQuery",
  "processing": "Processing",
  "prolog": "Prolog",
  "properties": ".properties",
  "protobuf": "Protocol Buffers",
  "pug": "Pug",
  "puppet": "Puppet",
  "pure": "Pure",
  "px": "PC-Axis",
  "py": "Python",
  "python": "Python",
  "q": "Q (kdb+ database)",
  "qml": "QML",
  "qore": "Qore",
  "r": "R",
  "racket": "Racket",
  "rb": "Ruby",
  "rbnf": "Routing Backus–Naur form",
  "reason": "Reason",
  "regex": "Regex",
  "renpy": "Ren'py",
  "rest": "reST (reStructuredText)",
  "rip": "Rip",
  "rkt": "Racket",
  "roboconf": "Roboconf",
  "robot": "Robot Framework",
  "robotframework": "Robot Framework",
  "rq": "SPARQL",
  "ruby": "Ruby",
  "rust": "Rust",
  "sas": "SAS",
  "sass": "Sass (Sass)",
  "scala": "Scala",
  "scheme": "Scheme",
  "scss": "Sass (Scss)",
  "shell": "Shell",
  "shell-session": "Shell session",
  "shortcode": "Shortcode",
  "sln": "Solution file",
  "smalltalk": "Smalltalk",
  "smarty": "Smarty",
  "solidity": "Solidity (Ethereum)",
  "solution-file": "Solution file",
  "soy": "Soy (Closure Template)",
  "sparql": "SPARQL",
  "splunk-spl": "Splunk SPL",
  "sqf": "SQF: Status Quo Function (Arma 3)",
  "sql": "SQL",
  "ssml": "SSML",
  "stylus": "Stylus",
  "svg": "SVG",
  "swift": "Swift",
  "t4": "T4 Text Templates (C#)",
  "t4-cs": "T4 Text Templates (C#)",
  "t4-templating": "T4 templating",
  "t4-vb": "T4 Text Templates (VB)",
  "tap": "TAP",
  "tcl": "Tcl",
  "tex": "TeX",
  "textile": "Textile",
  "toml": "TOML",
  "trig": "TriG",
  "ts": "TypeScript",
  "tsx": "React TSX",
  "tt2": "Template Toolkit 2",
  "turtle": "Turtle",
  "twig": "Twig",
  "typescript": "TypeScript",
  "uc": "UnrealScript",
  "unrealscript": "UnrealScript",
  "uscript": "UnrealScript",
  "vala": "Vala",
  "vb": "Visual Basic",
  "vbnet": "VB.Net",
  "velocity": "Velocity",
  "verilog": "Verilog",
  "vhdl": "VHDL",
  "vim": "vim",
  "visual-basic": "Visual Basic",
  "warpscript": "WarpScript",
  "wasm": "WebAssembly",
  "wiki": "Wiki markup",
  "xeora": "Xeora",
  "xeoracube": "XeoraCube",
  "xls": "Excel Formula",
  "xlsx": "Excel Formula",
  "xml": "XML",
  "xojo": "Xojo (REALbasic)",
  "xquery": "XQuery",
  "yaml": "YAML",
  "yml": "YAML",
  "zig": "Zig"
};

module.exports = function(options = {}) {
  return function(str, language) {
    if(!language) {
      // empty string means defer to the upstream escaping code built into markdown lib.
      return "";
    }

    let split = language.split("/");
    if( split.length ) {
      language = split.shift();
    }

    let html;
    if(language === "text") {
      html = str;
    } else {
      html = Prism.highlight(str, PrismLoader(language), language);
    }

    let hasHighlightNumbers = split.length > 0;
    let highlights = new HighlightLinesGroup(split.join("/"), "/");
    let lines = html.split("\n").slice(0, -1); // The last line is empty.

    lines = lines.map(function(line, j) {
      if(options.alwaysWrapLineHighlights || hasHighlightNumbers) {
        let lineContent = highlights.getLineMarkup(j, line);
        return lineContent;
      }
      return line;
    });

    return `<pre data-display-language="${Languages[language]}" class="language-${language}"><code class="language-${language}">${lines.join("<br>")}</code></pre>`;
  };
};
